# OUTLINE
 __1 Python basics : Setup, syntax & standard libraries__
        
 2 Pymatgen 1 : build a structure & write a vasp job
    
 3 Python + slurm + bash : launch a vasp job
    
 4 Pymatgen 2 : read a vasp job & plot DOS
    
 5 Matplotlib : make your own plots 
    
 6 Pymatgen 3 : advanced functionalities (disorder, bader, lobster ... )
    
 7 the read_write library : installation, work flow & examples


# Session 1 : Python Basics
## Installation of working station 
### Mandatory : python and jupyter notebook

CHeck that you have python installed by typing `python3` in the terminal. If you don't, install it : 

`sudo apt-get install python`
	
First install basic  jupyter notebook  

`pip3 install --upgrade pip && pip3 install jupyter` then launch with `jupyter notebook`

### Optionnal : improve your coding environment
* __Easy__ : install *JupyterLab* (more fancy web-based interface) [(try it first if you want)]()

`pip3 install jupyterlab` then launch with `jupyter lab`

* __All-inclusive__ : install [*VS-Code*](https://code.visualstudio.com/) (my personnal preference !)

Complete beautiful and fonctionnal IDE, microsoft BUT opensource, incredible plugins for python, jupyter & git !!!

`sudo snap install --classic code` or [download the .deb here](https://code.visualstudio.com/Download) and do `sudo apt install *.deb`

*Come on, its christmas, treat yourself and use a proper code editor ! *

* __old-school__ : if you are *emacs* fanatic : 

integrate jupyter via the [ein emacs package ](https://github.com/tkf/emacs-ipython-notebook) (emacs ipython notebook)

(beware plot are not interactive)

* __deprecated__ : sorry *vim* is not enough for what we want here ...

## Syntax : 
Variable names are a link to their values (pointer)

Therefore variable have no type, only values have type 

No variable declaration required (declaration 'on the fly')

Python has an efficient garbage collector, no need to suppress variables by hand

In [2]:
a = 2+3
print(a,'type', type(a))
a = 1.00005 
print(a,'type', type(a))
a = "hello world" 
print(a,'type', type(a))


5 type <class 'int'>
1.00005 type <class 'float'>
hello world type <class 'str'>


In [91]:
a = 1
b = a # the right part is evaluated and assigned to the left part (pointer)
a = 'minux' 
print(b) 

1


## Data structures : 
useful = list \[1\] // dict { "a": 1 }

less common = set {1} // tuple (1)

In [107]:
# LIST  = key is an int, value can be any object
# read / write value by number (start with 0)
L = [1,2,3]
L.append("soleil")
print( L, "// L[1] = ", L[1])


# DICT = key is a string, value can be any object
# read / write value by name
D = {"a" : 1, "b" : 2,"c" : 3}
D["d"]="soleil"
print( D, "// D['b'] = ", D["b"])


[1, 2, 3, 'soleil'] // L[1] =  2
{'a': 1, 'b': 2, 'c': 3, 'd': 'soleil'} // D['b'] =  2


In [108]:
# other types less usefull

# SET = list with unique members
# useful to avoid doubles
S = {1,2,3,"soleil",2,3,2,3}
print(S) 

# TUPLE = "immutable" list, cannot be modified after creation
# faster iteration than list 
T = (1,2,3, "soleil")
print(T[2])

{'soleil', 1, 2, 3}
3


## logical operators : 


In [6]:
# for loop
for a in [1,2,3] :
    print(a)

print("\n") #escaped character for line break

for a in "abc" : # string = list of letters
    print(a)

1
2
3


a
b
c


__indentation is MANDATORY__

In [7]:
for a in [1,2,3] :
    print(a)
print("linebreak outside loop \n")

for a in [1,2,3] :
    print(a)
    print("linebreak inside loop")

1
2
3
linebreak outside loop 

1
linebreak inside loop
2
linebreak inside loop
3
linebreak inside loop


In [5]:
# if loop
a = 2
if a >= 2 :
    print("a >= 2")
elif a < 1 : 
    print("a < 1")
else :
    print("a = 1")

a >= 2


In [28]:
# list comprehension 
simple_list = [ 2*a for a in [1,2,3,4,5,6,7]]
print("list comprehension : ", simple_list)

#range function (start at 0)
simple_list = [ 2*a for a in range(7)]
print("list comprehension using range() fct : ", simple_list)

# with condition
list_w_condition = [ 2*a for a in range(7) if 2*a<10 ]
print("list with condition : ", list_w_condition)

# dict comprehension with zip of 2 lists
dict_w_condition = { keyword : 2*value for keyword,value in zip("abcdefg",range(7)) if value%2==0}
print("dict comprehension with condition : ", dict_w_condition)
    

list comprehension :  [2, 4, 6, 8, 10, 12, 14]
list comprehension using range() fct :  [0, 2, 4, 6, 8, 10, 12]
list with condition :  [0, 2, 4, 6, 8]
dict comprehension with condition :  {'a': 0, 'c': 4, 'e': 8, 'g': 12}


### Exercise 
display all prime numbers between 0 and 20

In [ ]:
# this is the cell for the exercise ! 

In [24]:
# simple method
L = []
for n in range(2,20) : 
    prime = True
    for p in L :
        if n%p==0 :
            prime = False
    if prime : 
        L.append(n)
print(L)


[2, 3, 5, 7, 11, 13, 17, 19]


In [6]:
# same thing using for / break / else 
L = []
for n in range(2,20) : 
    for p in L :
        if n%p==0 :
            break # exit the for loop 
    else : # executed after a for loop if no break was encountered
        L.append(n)
print(L)

[2, 3, 5, 7, 11, 13, 17, 19]


In [15]:
# nested list comprehension
L = [n for n in range(2,20) if len([ p for p in range(2,n) if n%p==0]) == 0 ]
print(L)

[2, 3, 5, 7, 11, 13, 17, 19]


In [20]:
# the best way : less work, more readable, more reliable
from sympy import primerange # we import a function from a library (see below for more explanation)
print([ n for n in primerange(1, 20)])

[2, 3, 5, 7, 11, 13, 17, 19]


__take home message__ : if you want to do it, someone has already coded it (and probably better than you would)

## Object oriented : Functions, class & instances

__function__ : take several arguments and product several outputs

__class__ : contains values and functions (which are attributes)

__instance__ : Specific member of the class

### Functions

In [9]:
def x_by_2(number) :
        return 2*number	
a = 12
print(x_by_2) # function
print(x_by_2(a)) # value of the function

<function x_by_2 at 0x7efdcdadf378>
24


In [51]:
# there may be several inputs and outputs
def sum_and_diff_and_compare(a,b) :
        return (a+b,a-b,a>b)

sum_and_diff_and_compare(5,7)

(12, -2, False)

In [50]:
def computation_time(time_by_task, number_of_task):
        return time_by_task*number_of_task

print("\nArgument can be refeenced by position (order determines which is which)")
print(computation_time(1, 3))

print("\nreferenced by key word only (order does not count) ")
print(computation_time(time_by_task=1, number_of_task=3))
print(computation_time(number_of_task=3, time_by_task=1))

print( "\nReferenced by a mix of position and kw (here order is important)")
print(computation_time(1, number_of_task=3))
print(computation_time(3, time_by_task=1)) # error


Argument can be refeenced by position (order determines which is which)
3

referenced by key word (order does not count) 
3
3

Referenced by a mix of position and kw (in which case order is important)
3


TypeError: computation_time() got multiple values for argument 'time_by_task'

In [59]:
print("There may be optionnal arguments")
def computation_time(time_by_task, number_of_task, nb_of_nodes=1):
        return time_by_task*number_of_task/nb_of_nodes

print("explicit call to all arguments  Result :", 
                    computation_time(time_by_task=1, number_of_task=3,nb_of_nodes=3 ))        

print("default values provided in the function definition) : nb_of_nodes=1 Result  :",
                    computation_time(time_by_task=1, number_of_task=3)) # default to nb_of_nodes=1


There may be optionnal arguments
explicit call to all arguments  Result : 1.0
default values provided in the function definition) : nb_of_nodes=1 Result  : 3.0


### Class & instances

In [242]:
class Student(): # a class
    pass

print(Student) #  a class 

micheline = Student()
print(micheline) 
# Micheline is "one of the" students
# an object from the class Student (called an instance of the class)
# printed with hexadecimal adress pointer to unique memory location of that instance



<class '__main__.Student'>


In [243]:
# a object has attribute 
micheline.age = 24 # they can be written
print("micheline", micheline.age) # and they can be read

jean_jacques = Student()
jean_jacques.age = 12
print("jean_jacques", jean_jacques.age)

micheline 24
jean_jacques 12


In [249]:
# attribute can also be defined in the class itself
# these class attributes are the same for all
# these attributes can be variables ('work') or functions ('where_do_I_work')

class Student():
    work="ICGM" # shared by all = CLASS attribute

    def where_do_I_work(self):
        print("ICGM !!")

micheline = Student()
micheline.age = 24 # there are attribute specific to each INSTANCE, added after the initialization
print("micheline", micheline.age, micheline.work)
micheline.where_do_I_work()

jean_jacques = Student()
jean_jacques.age = 12
# we improve the string formatting
print("\njean_jacques is {} and works at {}".format(jean_jacques.age, jean_jacques.work)) 
micheline.where_do_I_work()


micheline 24 ICGM
ICGM !!

jean_jacques is 12 and works at ICGM
ICGM !!


In [250]:
# the __init__ mthod is called when creating a new instance (called instanciation)
# instance attributes can be setup at that moment 

class Student():
    work="ICGM" # shared by all 
    def __init__(self, age):
        self.age = age # attribute specific to each INSTANCE, added DURING the initialization

    def is_major(self):
        if self.age >=18 : 
            return True
        else :
            return False


micheline = Student(24) # __init__ function is called when creating the instance
print(type(micheline.is_major    )) 
# micheline.is_major is a functiion

print(type(micheline.is_major()  )) 
# micheline.is_major() is a boolean value : the result of the function 
# no need for argument, the value is stored within the instance 'micheline'

print("micheline can have a beer ? ",micheline.is_major() ) 

jean_jacques = Student(12)
print("jean_jacques can have a beer ? ",jean_jacques.is_major())

<class 'method'>
<class 'bool'>
micheline can have a beer ?  True
jean_jacques can have a beer ?  False


In [129]:
class Student():
    
    def __init__(self, age, name):
        self.age = age
        self.name = name

    
    def is_older_than(self, other_student) :
        if self.age > other_student.age : # comparing instance attribute with function argument
            return True
        else :
            return False

A = Student(24, "micheline")
B = Student(12,"jean_jacques")
print("{} is older than {} ? {} !!!".format(A.name,B.name, A.is_older_than(B) ))
# we give another instance as argument
# this makes the language very readable

micheline is older than jean_jacques ? True !!!


In [132]:
# class inheritance (subclass inherit attributes (variables, functions) and add new ones)
class StudentICGM(Student):
    def __init__(self, age, name):
        Student.__init__(self, age, name)

    def where_do_you_work(self):
        print("I work at ICGM ! youpi !")

A = StudentICGM(24, "micheline")
B = Student(12,"jean_jacques")
print("{} is older than {} ? {} !!!".format(A.name,B.name, A.is_older_than(B) )) # StudentICGM use function & attribute (name) from parent class
A.where_do_you_work()   # ok
B.where_do_you_work() # error because Student class does not have this function

micheline is older than jean_jacques ? True !!!
I work at ICGM ! youpi !


AttributeError: 'Student' object has no attribute 'where_do_you_work'

Now you can read Pymatgen source code or any other module and understand what is going on !!!

### Exercise
Create a class Researcher whith the attributes (Name, Lastname, field, topic)

`jean = Researcher("Jean","Vergnet","chemistry","anionic redox")`

Create a class function `jean.presentation` which returns "I'm Jean Vergnet, a chemistry researcher working on anionic redox"

Create a class function `jean.compare_field(another_reasearcher)` which tell if we work on related field or identical topic


In [ ]:
# space for exercise !

In [45]:
class Researcher():
    
    def __init__(self,name, lastname, field, topic):
        self.name = name
        self.lastname = lastname
        self.field = field
        self.topic = topic

    def presentation(self) : 
        # here we used the string.format() as follow "{instance.attribute}".format(instance)
        return "I'm {0.name} {0.lastname}, a {0.field} researcher working on {0.topic}".format(self)

    def compare_field(self, other_researcher) :
        if self.field == other_researcher.field : # comparison takes 2 "=" (definition takes only one "=")
            if self.topic == other_researcher.topic :
                print("{} & {} work in the exact same topic. WOW !".format(self.name, other_researcher.name))
            else :
                print("{} & {} are doing stuff related, not exactly the same but you know... related".format(self.name, other_researcher.name))
        else :
            print("{} & {} are doing completely different things !!".format(self.name, other_researcher.name))
            

In [46]:
jean = Researcher("Jean","Vergnet","chemistry","anionic redox")
print("\n",jean.presentation())
pierre = Researcher("Pierre","Bourdieu","Social Sciences","social reproduction")
print("\n",pierre.presentation())
jean.compare_field(pierre)
alexander = Researcher("Alexander","Shulgin","chemistry","synthesis")
print("\n",alexander.presentation())
jean.compare_field(alexander)


 I'm Jean Vergnet, a chemistry researcher working on anionic redox

 I'm Pierre Bourdieu, a Social Sciences researcher working on social reproduction
Jean & Pierre are doing completely different things !!

 I'm Alexander Shulgin, a chemistry researcher working on synthesis
Jean & Alexander are doing stuff related, not exactly the same but you know... related


## Modules and libraries
__module__ : a .py file which contains Classes, functions and values 

importing a module = read an external .py file at execution time and allow to acess its functions

__library__ : several interdependant modules which allow specific task

library can be acessed at the top level (1 module which imports all the others) or more specifically by targeting a sub-module

some libraries can use binaries coded in C or fortran for efficiency (math, numpy, scipy, cpython)

In [14]:
import math # import the whole module
print(math.log(1000)) # we use the attribute (function) "log" of the module math
print(math.exp(15))

6.907755278982137
3269017.3724721107


In [15]:
from math import log10 # import only the desired function
log10(1000) # we use directly the function log10, without reference to its module

3.0

### Useful standard librairies 
__os  & shutil__ : navigate and maniputate files and folders (~ bash)

__numpy & Scipy__ : heavy number manipulation (matrix) made simple (coded in C => very efficient) 

In [16]:
import os 
cwd = os.getcwd()
path_to_tmp_folder = os.path.join(cwd,"test_python")
os.mkdir(path_to_tmp_folder)
print("is dir ?",os.path.isdir(path_to_tmp_folder))
print("is file ?",os.path.isfile(path_to_tmp_folder))
os.chdir(path_to_tmp_folder)
print(os.getcwd())

is dir ? True
is file ? False
/home/jvergnet/Documents/scripts/read_write/test_python


In [17]:
import shutil
os.chdir(cwd)
shutil.rmtree(path_to_tmp_folder)
print("dir still exist ?" , os.path.exists(path_to_tmp_folder))


dir still exist ? False


In [48]:
import numpy as np
print("Multi dimensionnal matrices") 
print(np.array([[0,1,2],[4,7,8]]),"\n")

print("Vector construction")
print("1D -vector\n",np.linspace(0,10, num=6))
print("\n2D - matrix\n",np.eye(4),"\n")
print("\n3D and more - tensor\n",np.ones((2,3,4)),"\n")


Multi dimensionnal matrices
[[0 1 2]
 [4 7 8]] 

Vector construction
1D -vector
 [ 0.  2.  4.  6.  8. 10.]

2D - matrix
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 


3D and more - tensor
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]] 



In [19]:
print("clever indexing \n select first colum of eye matrix \n", np.eye(4)[:,1] )

print("powerfull operations")
print("\nscalar\n", np.sin(np.eye(4)*np.pi/4))
print("\nterm by term\n", np.subtract(np.ones((4,4)), np.eye(4)))

clever indexing 
 select first colum of eye matrix 
 [0. 1. 0. 0.]
powerfull operations

scalar
 [[0.70710678 0.         0.         0.        ]
 [0.         0.70710678 0.         0.        ]
 [0.         0.         0.70710678 0.        ]
 [0.         0.         0.         0.70710678]]

term by term
 [[0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 0.]]
